import React from 'react';
import Head from 'next/head';

interface IheadsProps {
	title?: string;
	content?: string;
}

const Heads: React.FunctionComponent<IheadsProps> = ({ title, content }) => {
	return (
		<Head>
			<title>MyApp {title}</title>
			<meta name="description" content={content} />
		</Head>
	);
};
Heads.defaultProps = {
	title: '',
	content: 'Generated by create next app',
};

export default Heads;
