import React from 'react';
import Head from 'next/head';
import Navs from './Navs';

interface IlayoutProps {
	children: React.ReactNode;
}

const Layout: React.FunctionComponent<IlayoutProps> = ({ children }) => {
	return (
		<section>
			<Head>
				<title>MyApp</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<Navs />
			<div>{children}</div>
		</section>
	);
};

export default Layout;
