import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>MyApp</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>

			<div>index</div>
		</div>
	);
};

export default Home;
